In [20]:
import anthropic
import json
import numpy as np
import pandas as pd

client = anthropic.Anthropic()
def get_car_specs(make, model, year, fuel_type):
    prompt = f"""For the {year} {make} {model} with fuel type "{fuel_type}", provide the following in strict JSON format only, no other text:
{{
  "cylinders": <number, integer, or null if electric with no engine>,
  "fuel_efficiency_l_per_100km": <number, float, or null if fully electric>,
  "country_of_origin": "<string>"
}}
Consider that the fuel type may indicate a specific trim/variant (e.g. M-performance, Hybrid, Electric) which can have different specs than the base model, and that specs can vary by model year due to generation changes or manufacturing location shifts.
If unsure about a specific value, use null."""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=200,
        messages=[{"role": "user", "content": prompt}]
    )
    
    text = response.content[0].text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    return json.loads(text)

In [21]:
df= pd.read_csv("../PreEDAVersion.csv")

In [22]:
unique_cars = df[["make_model", "fuel_type"]].drop_duplicates().reset_index(drop=True)
unique_cars

                        make_model            fuel_type
0             2022 Lincoln Corsair                  Gas
1               2026 Jeep Cherokee  Gas/Electric Hybrid
2              2026 Hyundai Tucson                  Gas
3                  2024 Mazda CX-5                  Gas
4                  2021 Ford F-150                  Gas
...                            ...                  ...
4660       2016 Chevrolet Suburban                  Gas
4661    2023 Mercedes-Benz S-Class                  Gas
4662       2009 Porsche Cayman 718                  Gas
4663  2009 Mercedes-Benz CLK-Class                  Gas
4664        2018 Audi A5 Cabriolet                  Gas

[4665 rows x 2 columns]

In [23]:
def get_car_specs(make_model, fuel_type):
    prompt = f"""For the car "{make_model}" with fuel type "{fuel_type}", provide the following in strict JSON format only, no other text:
{{
  "cylinders": <number, integer, or null if electric with no engine>,
  "fuel_efficiency_l_per_100km": <number, float, or null if fully electric>,
  "country_of_origin": "<string>"
}}
Consider that the fuel type may indicate a specific trim/variant (e.g. M-performance, Hybrid, Electric) which can have different specs than the base model, and that specs can vary by model year due to generation changes or manufacturing location shifts.
If unsure about a specific value, use null."""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=200,
        messages=[{"role": "user", "content": prompt}]
    )
    
    text = response.content[0].text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    return json.loads(text)

In [ ]:
unique_cars = df[["make_model", "fuel_type"]].drop_duplicates().reset_index(drop=True)

results = []

for idx, row in unique_cars.iterrows():
    try:
        specs = get_car_specs(row["make_model"], row["fuel_type"])
        specs["make_model"] = row["make_model"]
        specs["fuel_type"] = row["fuel_type"]
        print(f"Success for {row['make_model']} ({row['fuel_type']})")
        results.append(specs)
    except Exception as e:
        print(f"Failed for {row['make_model']} ({row['fuel_type']}): {e}")
        results.append({"make_model": row["make_model"], "fuel_type": row["fuel_type"],
                        "cylinders": None, "fuel_efficiency_l_per_100km": None,
                        "country_of_origin": None})

specs_df = pd.DataFrame(results).to_csv("New Spec")
#df = df.merge(specs_df, on=["make_model", "fuel_type"], how="left")

Success for 2022 Lincoln Corsair (Gas)
Success for 2026 Jeep Cherokee (Gas/Electric Hybrid)
Success for 2026 Hyundai Tucson (Gas)
Success for 2024 Mazda CX-5 (Gas)
Success for 2021 Ford F-150 (Gas)
Success for 2024 Land Rover Defender (Gas)
Success for 2022 Honda Passport (Gas)
Success for 2023 Kia Seltos (Gas)
Success for 2023 Genesis GV70 (Gas)
Success for 2022 Audi S5 Sportback (Gas)
Success for 2019 Mazda Mazda3 (Gas)
Success for 2020 Subaru Outback (Gas)
Success for 2020 Land Rover Defender (Gas/Electric Hybrid)
Success for 2025 Toyota Prius (Gas/Electric Hybrid)
Success for 2022 BMW X5 (Electric)
Success for 2025 Subaru WRX (Gas)
Success for 2020 Infiniti QX60 (Gas)
Success for 2021 Ford Bronco Sport (Gas)
Success for 2017 Honda Civic Sedan (Gas)
Success for 2023 Nissan Versa (Gas)
Success for 2015 Mercedes-Benz GLA (Gas)
Success for 2011 Land Rover Range Rover Sport (Gas)
Success for 2024 Volkswagen Taos (Gas)
Success for 2022 Volkswagen Tiguan (Gas)
Success for 2025 Kia Carnival (Gas)
Success for 2014 Porsche Panamera (Gas)
Success for 2025 Volkswagen Atlas (Gas)
Success for 2025 Toyota 4-Runner (Gas)
Success for 2023 Buick Envision (Gas)
Success for 2024 Toyota RAV 4 (Gas)
Success for 2023 Mercedes-Benz GLC (Gas)
Success for 2019 Land Rover Range Rover Evoque (Gas)
Success for 2022 Audi Q8 (Gas/Electric Hybrid)
Success for 2021 Honda Pilot (Gas)
Success for 2023 BMW X1 (Gas)
Success for 2021 BMW 8 Series Gran Coupe (Gas)
Success for 2019 Audi A5 Coupe (Gas)
Success for 2022 Hyundai Elantra (Gas)
Success for 2025 BMW M4 (Gas)
Success for 2022 Honda Civic Sedan (Gas)
Success for 2023 Toyota RAV 4 Hybrid (Gas/Electric Hybrid)
Success for 2025 Kia Telluride (Gas)
Success for 2022 Audi A5 Sportback (Gas/Electric Hybrid)
Success for 2019 Volkswagen Tiguan (Gas)
Success for 2021 Toyota RAV 4 Hybrid (Gas/Electric Hybrid)
Success for 2024 Toyota Tacoma (Gas)
Success for 2025 BMW 3 Series (Gas)
Success for 2018 BMW 5 Series (Gas)
Success for 2024 Volkswagen Tiguan (Gas)
Success for 2017 Volkswagen Tiguan (Gas)
Success for 2023 Ford Escape (Gas)
Success for 2014 Volkswagen Tiguan (Gas)
Success for 2025 Hyundai Palisade (Gas)
Success for 2023 BMW X5 (Gas)
Success for 2024 Honda CR-V Hybrid (Gas/Electric Hybrid)
Success for 2020 Honda Insight (Gas/Electric Hybrid)
Success for 2019 Audi A5 Sportback (Gas)
Success for 2024 Ford Mustang Mach-E (Electric)
Success for 2020 Land Rover Range Rover Evoque (Gas/Electric Hybrid)
Success for 2022 Acura RDX (Gas)
Success for 2023 Toyota Corolla Cross (Gas)
Success for 2018 Honda CR-V (Gas)
Success for 2018 Audi A3 Sedan (Gas)
Success for 2024 MINI 5 Door (Gas)
Success for 2022 Volkswagen Taos (Gas)
Success for 2024 Audi Q5 (Gas)
Success for 2011 Honda CR-V (Gas)
Success for 2019 Acura RDX (Gas)
Success for 2020 Honda CR-V (Gas)
Success for 2026 Jeep Wrangler (Gas)
Success for 2016 Porsche Macan (Gas)
Success for 2023 Tesla Model Y (Electric)
Success for 2013 BMW X6 (Gas)
Success for 2018 Audi Q7 (Gas)
Success for 2018 Land Rover Discovery Sport (Gas)
Success for 2021 Hyundai Santa Fe (Gas)
Success for 2022 Toyota Tundra Hybrid (Gas/Electric Hybrid)
Success for 2018 Volkswagen Tiguan (Gas)
Success for 2022 Acura ILX (Gas)
Success for 2021 Ford Bronco (Gas)
Success for 2024 Toyota RAV 4 Hybrid (Gas/Electric Hybrid)
Success for 2024 Jeep Grand Cherokee L (Gas)
Success for 2018 Audi S5 Sportback (Gas)
Success for 2023 Lexus NX (Gas)
Success for 2017 Lexus IS (Gas)
Success for 2021 Honda CR-V (Gas)
Success for 2025 Volkswagen Golf R (Gas)
Success for 2024 Honda CR-V (Gas)
Success for 2025 RAM 1500 (Gas)
Success for 2018 Hyundai Santa Fe Sport (Gas)
Success for 2023 Honda CR-V (Gas)
Success for 2020 Toyota Camry (Gas)
Success for 2019 RAM 1500 (Gas)
Success for 2019 Mazda Mazda3 Sport (Gas)
Success for 2023 Honda CR-V Hybrid (Gas)
Success for 2016 Mazda Mazda3 (Gas)
Success for 2022 Hyundai Santa Fe (Gas)
Success for 2021 Jeep Wrangler (Gas)
Success for 2019 Acura MDX (Gas)
Success for 2020 Land Rover Range Rover Velar (Gas)
Success for 2022 BMW X1 (Gas)
Success for 2022 Mazda CX-30 (Gas)
Success for 2018 Infiniti QX60 (Gas)
Success for 2024 Jeep Compass (Gas)
Success for 2025 Mercedes-Benz GLC (Gas/Electric Hybrid)
Success for 2025 Audi Q7 (Gas)
Success for 2022 Subaru BRZ (Gas)
Success for 2023 Jeep Wrangler (Gas)
Success for 2021 Hyundai Elantra (Gas)
Success for 2021 Nissan Rogue (Gas)
Success for 2024 Chevrolet Silverado 1500 (Gas)
Success for 2017 Mercedes-Benz E-Class (Gas)
Success for 2025 Honda CR-V (Gas)
Success for 2023 Infiniti QX50 (Gas)
Success for 2024 Honda Civic Sedan (Gas)
Success for 2023 Toyota Corolla Sedan (Gas)
Success for 2021 Toyota Corolla Sedan (Gas)
Success for 2023 Mazda CX-9 (Gas)
Success for 2023 Land Rover Range Rover Sport (Gas)
Success for 2022 Lincoln Nautilus (Gas)
Success for 2019 Toyota RAV 4 Hybrid (Gas/Electric Hybrid)
Success for 2026 Land Rover Range Rover Velar (Gas)
Success for 2017 Mazda CX-5 (Gas)
Success for 2024 Nissan Pathfinder (Gas)
Success for 2018 Mercedes-Benz E-Class (Gas)
Success for 2019 Honda HR-V (Gas)
Success for 2022 Volkswagen Golf GTI (Gas)
Success for 2019 BMW X2 (Gas)
Success for 2018 Subaru WRX (Gas)
Success for 2023 Subaru BRZ (Gas)
Success for 2023 Land Rover Range Rover Evoque (Gas)
Success for 2020 Lexus UX (Gas/Electric Hybrid)
Success for 2023 Mazda CX-50 (Gas)
Success for 2019 Honda CR-V (Gas)
Success for 2012 Mazda Mazda3 (Gas)
Success for 2020 Mazda CX-30 (Gas)
Success for 2019 Lexus IS (Gas)
Success for 2023 RAM 1500 (Gas)
Success for 2017 Nissan Frontier (Gas)
Success for 2024 Toyota Prius (Gas/Electric Hybrid)
Success for 2012 Chevrolet Colorado (Gas)
Success for 2019 Mazda CX-5 (Gas)
Success for 2016 Toyota RAV 4 (Gas)
Success for 2023 Hyundai Kona Electric (Electric)
Success for 2022 BMW X5 (Gas)
Success for 2016 Mazda CX-5 (Gas)
Success for 2026 Toyota 4-Runner (Gas)
Success for 2017 Toyota Prius (Gas/Electric Hybrid)
Success for 2022 Hyundai Tucson (Gas)
Success for 2020 Honda HR-V (Gas)
Success for 2024 Mazda Mazda3 (Gas)
Success for 2021 Toyota Highlander (Gas)
Success for 2023 Hyundai Elantra (Gas)
Success for 2018 Kia Sorento (Gas)
Success for 2016 Honda CR-V (Gas)
Success for 2021 GMC Yukon (Gas)
Success for 2015 Mazda Mazda3 (Gas)
Success for 2023 MINI Countryman (Gas)
Success for 2020 Mercedes-Benz GLC (Gas)
Success for 2021 Toyota RAV 4 (Gas)
Success for 2021 Toyota RAV 4 (Gas/Electric Hybrid)
Success for 2018 Porsche Macan (Gas)
Success for 2021 Toyota Sienna (Gas/Electric Hybrid)
Success for 2019 Mercedes-Benz C-Class Coupe (Gas)
Success for 2023 BMW 4 Series (Gas)
Success for 2023 Chevrolet Blazer (Gas)
Success for 2023 Volkswagen Tiguan (Gas)
Success for 2023 Mazda Mazda3 Sport (Gas)
Success for 2023 Land Rover Range Rover Velar (Gas)
Success for 2024 Lexus TX (Gas)
Success for 2019 Chevrolet Silverado 1500 (Gas)
Success for 2018 Mazda Mazda3 (Gas)
Success for 2023 Hyundai Tucson Hybrid (Gas/Electric Hybrid)
Success for 2015 Honda Civic Sedan (Gas)
Success for 2025 BMW X2 (Gas)
Success for 2013 Honda Civic Sedan (Gas)
Success for 2025 Kia K4 (Gas)
Success for 2022 Toyota Camry (Gas)
Success for 2025 Audi Q3 (Gas)
Success for 2022 Jeep Wrangler Unlimited (Electric)
Success for 2019 BMW 3 Series (Gas)
Success for 2022 Mercedes-Benz GLC (Gas/Electric Hybrid)
Success for 2022 RAM 1500 (Gas)
Success for 2021 Hyundai Palisade (Gas)
Success for 2022 Ford F-150 (Gas)
Success for 2015 Honda CR-V (Gas)
Success for 2025 Mazda CX-70 MHEV (Gas)
Success for 2024 BMW X5 (Gas)
Success for 2017 Volvo XC90 (Gas)
Success for 2026 Ford F-150 (Gas)
Success for 2019 Toyota RAV 4 (Gas)
Success for 2022 Honda CR-V (Gas)
Success for 2022 Genesis GV70 (Gas)
Success for 2017 Volvo XC90 Hybrid (Gas/Electric Hybrid)
Success for 2018 Toyota Camry (Gas)
Success for 2023 Nissan Z (Gas)
Success for 2023 Nissan Rogue (Gas)
Success for 2024 Acura RDX (Gas)
Success for 2017 Audi Q5 (Gas)
Success for 2020 Ford Escape (Gas)
Success for 2016 Volkswagen Tiguan (Gas)
Success for 2020 Mitsubishi Eclipse Cross (Gas)
Success for 2020 Ford F-150 (Gas)
Success for 2015 Acura TLX (Gas)
Success for 2022 Lexus NX (Gas)
Success for 2024 Volkswagen Jetta (Gas)
Success for 2016 BMW 4 Series (Gas)
Success for 2017 Audi SQ5 (Gas)
Success for 2023 Acura MDX (Gas)
Success for 2018 Honda Pilot (Gas)
Success for 2020 Hyundai Tucson (Gas)
Success for 2015 BMW X4 (Gas)
Success for 2017 Toyota 4-Runner (Gas)
Success for 2022 Audi Q5 (Gas)
Success for 2018 BMW 3 Series (Gas)
Success for 2020 BMW X6 (Gas)
Success for 2022 Hyundai Venue (Gas)
Success for 2023 Toyota RAV 4 (Gas)
Success for 2017 Toyota RAV 4 (Gas)
Success for 2024 Nissan Sentra (Gas)
Success for 2024 Buick Envista (Gas)
Success for 2022 Mercedes-Benz GLE (Gas)
Success for 2019 Hyundai Tucson (Gas)
Success for 2024 Toyota RAV 4 (Gas/Electric Hybrid)
Success for 2023 Kia Sportage (Gas)
Success for 2018 Jeep Cherokee (Gas)
Success for 2013 Dodge Grand Caravan (Gas)
Success for 2010 Toyota RAV 4 (Gas)
Success for 2025 Toyota RAV 4 Hybrid (Gas/Electric Hybrid)
Success for 2022 Volvo XC90 (Gas)
Success for 2025 Dodge Durango (Gas)
Success for 2018 Acura RDX (Gas)
Success for 2020 Toyota Highlander Hybrid (Gas/Electric Hybrid)
Success for 2023 Hyundai Venue (Gas)
Success for 2012 Acura MDX (Gas)
Success for 2017 Chevrolet Silverado 1500 (Gas)
Success for 2012 Land Rover Range Rover Sport (Gas)
Success for 2019 Ford Explorer (Gas)
Success for 2017 Audi A3 (Gas)
Success for 2022 Volkswagen Atlas (Gas)
Success for 2022 Land Rover Range Rover Velar (Gas)
Success for 2023 Chevrolet Silverado 1500 (Gas)
Success for 2018 Toyota Prius (Gas/Electric Hybrid)
Success for 2022 Kia Sorento Plug-In Hybrid (Electric)
Success for 2021 Toyota RAV 4 (Electric)
Success for 2017 Ford Explorer (Gas)
Success for 2019 Mazda CX-9 (Gas)
Success for 2018 Mazda CX-3 (Gas)
Success for 2020 Mazda CX-5 (Gas)
Success for 2017 Honda CR-V (Gas)
Success for 2025 BMW 2 Series (Gas)
Success for 2021 Toyota Prius (Gas/Electric Hybrid)
Success for 2021 Tesla Model 3 (Electric)
Success for 2022 Ford Mustang Mach-E (Electric)
Success for 2025 Honda CR-V Hybrid (Gas/Electric Hybrid)
Success for 2024 Hyundai Palisade (Gas)
Success for 2022 Audi Q3 (Gas)
Success for 2019 Infiniti QX80 (Gas)
Success for 2021 BMW X3 (Gas)
Success for 2022 Honda Pilot (Gas)
Success for 2024 Subaru Crosstrek (Gas)
Success for 2017 GMC Acadia (Gas)
Success for 2018 Jeep Wrangler JK (Gas)
Success for 2021 Jeep Grand Cherokee (Gas)
Success for 2017 BMW X3 (Gas)
Success for 2021 Mercedes-Benz GLE (Gas)
Success for 2015 Toyota 4-Runner (Gas)
Success for 2023 Ford Bronco Sport (Gas)
Success for 2025 Hyundai Elantra Hybrid (Gas/Electric Hybrid)
Success for 2023 Audi A3 Sedan (Gas)
Success for 2018 BMW X1 (Gas)
Success for 2021 Acura RDX (Gas)
Success for 2020 Nissan Armada (Gas)
Success for 2017 BMW X5 (Gas)
Success for 2019 Mercedes-Benz C-Class Sedan (Gas)
Success for 2025 Honda Civic Type R (Gas)
Success for 2022 Kia Seltos (Gas)
Success for 2025 Mercedes-Benz GLC (Gas)
Success for 2025 Kia Sorento Hybrid (Gas)
Success for 2023 Hyundai Santa Fe (Gas)
Success for 2023 Audi Q5 (Gas)
Success for 2018 RAM 1500 (Gas)
Success for 2012 Porsche Cayenne (Gas)
Success for 2024 Mercedes-Benz GLE (Gas)
Success for 2020 Mercedes-Benz C-Class Wagon (Gas)
Success for 2018 Toyota Sienna (Gas)
Success for 2022 Hyundai Palisade (Gas)
Success for 2023 Volvo XC60 (Gas)
Success for 2023 Toyota Highlander (Gas)
Success for 2020 BMW 3 Series (Gas)
Success for 2018 Honda Civic Sedan (Gas)
Success for 2024 Mitsubishi Eclipse Cross (Gas)
Success for 2024 Volkswagen Atlas (Gas)
Success for 2017 Acura MDX (Gas)
Success for 2024 Toyota Sienna (Gas/Electric Hybrid)
Success for 2016 Toyota Tundra (Gas)
Success for 2021 Ford Mustang Mach-E (Electric)
Success for 2016 Land Rover Range Rover Sport (Gas)
Success for 2023 Honda CR-V Hybrid (Gas/Electric Hybrid)
Success for 2018 Mazda CX-5 (Gas)
Success for 2021 Chevrolet Corvette (Gas)
Success for 2022 Toyota Corolla Sedan (Gas)
Success for 2018 Audi S5 Coupe (Gas)
Success for 2020 Ford Transit Cargo Van (Gas)
Success for 2026 Volvo XC90 (Gas)
Success for 2012 Honda Civic Sedan (Gas)
Success for 2022 Audi A4 Sedan (Gas)
Success for 2021 BMW X5 (Gas/Electric Hybrid)
Success for 2020 Porsche Macan (Gas)
Success for 2018 Toyota RAV 4 (Gas)
Success for 2013 Ford Taurus (Gas)
Success for 2020 Mercedes-Benz GLE (Gas)
Success for 2020 Porsche Cayman 718 GT4 (Gas)
Success for 2022 Kia Carnival (Gas)
Success for 2021 Dodge Challenger (Gas)
Success for 2016 Mercedes-Benz CLA (Gas)
Success for 2019 Volkswagen Jetta (Gas)
Success for 2022 Mazda CX-5 (Gas)
Success for 2019 Audi Q5 (Gas)
Success for 2023 Hyundai Santa Cruz (Gas)
Success for 2025 Tesla Model Y (Electric)
Success for 2022 Mercedes-Benz E-Class (Gas)
Success for 2017 Mercedes-Benz GLC (Gas)
Success for 2018 BMW X3 (Gas)
Success for 2022 Nissan Rogue (Gas)
Success for 2022 Acura TLX (Gas)
Success for 2024 Infiniti QX60 (Gas)
Success for 2023 Jeep Grand Cherokee (Gas)
Success for 2017 Toyota Highlander (Gas)
Success for 2024 Mercedes-Benz C-Class Sedan (Gas)
Success for 2023 Toyota Camry (Gas)
Success for 2023 Audi S5 Sportback (Gas)
Success for 2024 MINI 3 Door (Electric)
Success for 2024 Audi Q7 (Gas)
Success for 2016 Volvo XC90 Hybrid (Gas/Electric Hybrid)
Success for 2018 MINI 5 Door (Gas)
Success for 2013 Nissan Altima (Gas)
Success for 2024 Dodge Durango (Gas)
Success for 2023 Lexus NX (Gas/Electric Hybrid)
Success for 2016 Volvo XC90 (Gas)
Success for 2013 Ford Fusion (Gas)
Success for 2017 BMW 5 Series (Gas)
Success for 2023 Honda Accord Hybrid (Gas/Electric Hybrid)
Success for 2019 Mitsubishi Outlander (Gas)
Success for 2023 Lexus RX (Gas)
Success for 2023 Audi Q3 (Gas)
Success for 2025 BMW X5 (Gas)
Success for 2025 Hyundai Elantra (Gas)
Success for 2021 Porsche Cayenne (Gas)
Success for 2025 GMC Sierra 1500 (Gas)
Success for 2016 GMC Sierra 1500 (Gas)
Success for 2023 Mazda MX-5 Miata RF (Gas)
Success for 2023 GMC Sierra 1500 (Gas)
Success for 2015 Subaru Forester (Gas)
Success for 2022 Hyundai Kona (Gas)
Success for 2023 Ford F-150 (Gas/Electric Hybrid)
Success for 2016 Hyundai Sonata (Gas)
Success for 2024 Lexus NX (Gas)
Success for 2022 Mercedes-Benz GLB (Gas)
Success for 2023 Lexus LX (Gas)
Success for 2025 Toyota RAV 4 (Gas)
Success for 2020 Kia Forte 5 (Gas)
Success for 2024 Chevrolet Tahoe (Gas)
Success for 2024 Volvo XC60 Recharge (Gas)
Success for 2024 Lexus UX (Gas/Electric Hybrid)
Success for 2022 Toyota Tundra (Gas)
Success for 2022 MINI Countryman (Gas/Electric Hybrid)
Success for 2024 RAM 3500 (Gas)
Success for 2023 Hyundai Palisade (Gas)
Success for 2022 Lexus NX (Gas/Electric Hybrid)
Success for 2020 BMW 4 Series (Gas)
Success for 2020 Chevrolet Tahoe (Gas)
Success for 2022 BMW X5 (Gas/Electric Hybrid)
Success for 2023 BMW 8 Series Gran Coupe (Gas)
Failed for 2023 Tesla Model 3 (Gas): Extra data: line 8 column 1 (char 105)
Success for 2023 Honda Civic Sedan (Gas)
Success for 2022 Infiniti QX50 (Gas)
Success for 2021 Toyota Highlander Hybrid (Gas/Electric Hybrid)
Success for 2020 Porsche Cayenne (Gas/Electric Hybrid)
Success for 2019 Mercedes-Benz CLS-Class (Gas)
Success for 2022 Subaru Ascent (Gas)
Success for 2020 Volkswagen Golf Standard Model (Gas)
Success for 2018 Chevrolet Cruze (Gas)
Success for 2026 Hyundai Santa Fe Hybrid (Gas/Electric Hybrid)
Success for 2021 Volkswagen Jetta (Gas)
Success for 2023 BMW X4 (Gas)
Success for 2024 Mercedes-Benz CLA (Gas)
Success for 2025 MINI Countryman (Gas)
Success for 2019 Honda Civic Sedan (Gas)
Success for 2024 GMC Canyon (Gas)
Success for 2019 Kia Sorento (Gas)
Success for 2021 Mercedes-Benz GLS (Gas)
Success for 2022 Hyundai Santa Cruz (Gas)
Success for 2023 Toyota RAV 4 Hybrid (Gas)
Success for 2017 Audi A7 (Gas)
Success for 2013 Honda Civic Coupe (Gas)
Success for 2022 Toyota RAV 4 (Gas)
Success for 2021 Ford Explorer (Gas)
Success for 2024 Jeep Wrangler (Gas)
Success for 2024 Nissan Rogue (Gas)
Success for 2020 Audi Q3 (Gas)
Success for 2023 Nissan Pathfinder (Gas)
Success for 2025 Genesis GV70 (Gas)
Success for 2022 Acura MDX (Gas)
Success for 2023 Mazda CX-30 (Gas)
Success for 2019 Toyota Highlander (Gas)
Success for 2021 BMW X4 (Gas)
Success for 2025 Lexus UX (Gas/Electric Hybrid)
Success for 2023 Volkswagen Taos (Gas)
Success for 2024 Honda Pilot (Gas)
Success for 2010 Toyota Camry (Gas)
Success for 2020 Acura RDX (Gas)
Success for 2021 Jeep Gladiator (Gas)
Success for 2020 GMC Terrain (Gas)
Success for 2024 Nissan Z (Gas)
Success for 2015 Ford Focus (Gas)
Success for 2018 Mercedes-Benz GLC (Gas)
Success for 2024 GMC Terrain (Gas)
Success for 2024 BMW X6 (Gas/Electric Hybrid)
Success for 2023 Mercedes-Benz GLB (Gas)
Success for 2021 Mercedes-Benz GLE (Gas/Electric Hybrid)
Success for 2021 Volkswagen Tiguan (Gas)
Success for 2022 Kia Forte (Gas)
Success for 2008 Honda CR-V (Gas)
Success for 2019 Toyota Corolla Hatchback 5-Door (Gas)
Success for 2022 Dodge Charger (Gas)
Success for 2018 BMW 4 Series Gran Coupe (Gas)
Success for 2025 Jeep Wrangler (Gas)
Success for 2017 Land Rover Range Rover Sport (Gas)
Success for 2023 Mercedes-Benz CLA (Gas)
Success for 2022 Land Rover Range Rover Sport (Gas)
Success for 2015 Audi A4 (Gas)
Success for 2009 Acura TL (Gas)
Success for 2017 Chrysler Pacifica (Gas)
Success for 2026 RAM 1500 (Gas)
Success for 2023 Honda HR-V (Gas)
Success for 2016 Audi Q5 (Gas/Electric Hybrid)
Success for 2019 Mercedes-Benz SLC (Gas)
Success for 2024 Honda HR-V (Gas)
Success for 2023 Hyundai Sonata (Gas)
Success for 2025 Nissan Rogue (Gas)
Success for 2024 BMW X3 (Gas)
Success for 2010 Toyota Corolla Sedan (Gas)
Success for 2015 Lexus RX (Gas)
Success for 2025 Honda Pilot (Gas)
Success for 2025 BMW X3 (Gas/Electric Hybrid)
Success for 2015 BMW 4 Series (Gas)
Success for 2026 Hyundai Palisade Hybrid (Gas/Electric Hybrid)
Success for 2022 Toyota Venza (Gas/Electric Hybrid)
Success for 2019 Mazda CX-3 (Gas)
Success for 2022 Ford Expedition (Gas)
Success for 2025 Toyota Sienna (Gas)
Success for 2013 Hyundai Santa Fe (Gas)
Success for 2014 Lexus IS (Gas)
Success for 2019 Acura ILX (Gas)
Success for 2024 Lincoln Corsair (Electric)
Success for 2024 Audi SQ5 (Gas)
Success for 2021 Audi Q5 (Gas/Electric Hybrid)
Success for 2024 Lexus IS (Gas)
Success for 2021 BMW X6 (Gas)
Success for 2024 Mazda Mazda3 Sport (Gas)
Success for 2010 Toyota Prius (Gas/Electric Hybrid)
Success for 2022 GMC Terrain (Gas)
Success for 2016 Porsche Cayenne (Gas)
Success for 2015 Land Rover Range Rover Sport (Gas)
Success for 2024 Hyundai Elantra (Gas)
Success for 2023 Subaru Ascent (Gas)
Success for 2019 Lexus UX (Gas/Electric Hybrid)
Success for 2024 Hyundai Santa Fe (Gas)
Success for 2022 Audi Q5 Sportback (Gas)
Success for 2024 Chevrolet Blazer EV (Electric)
Success for 2016 BMW M2 (Gas)
Success for 2018 Chevrolet Traverse (Gas)
Success for 2025 RAM 2500 (Gas)
Success for 2024 Honda Accord Hybrid (Gas/Electric Hybrid)
Success for 2022 Chevrolet Silverado 1500 (Gas)
Success for 2020 Honda Passport (Gas)
Success for 2021 Jeep Wrangler Unlimited (Gas)
Success for 2022 Mercedes-Benz AMG GT (Gas/Electric Hybrid)
Success for 2016 Toyota Venza (Gas)
Success for 2021 Jeep Wrangler Unlimited (Gas/Electric Hybrid)
Success for 2016 Honda Accord Coupe (Gas)
Success for 2025 Volkswagen Jetta (Gas)
Success for 2023 GMC Canyon (Gas)
Success for 2016 Volkswagen Golf Standard Model (Gas)
Success for 2022 Mitsubishi Outlander (Gas)
Success for 2013 BMW 3 Series (Gas)
Success for 2022 Ford Mustang Fastback (Gas)
Success for 2024 Ford F-150 (Gas)
Success for 2026 Honda Passport (Gas)
Success for 2018 Ford F-150 (Gas)
Success for 2025 Nissan Kicks (Gas)
Success for 2020 Honda Civic Sedan (Gas)
Success for 2022 Chevrolet Traverse (Gas)
Success for 2016 Honda Accord Sedan (Gas)
Success for 2017 Toyota Yaris (Gas)
Success for 2023 Nissan Qashqai (Gas)
Success for 2025 Mazda CX-50 (Gas)
Success for 2024 RAM 1500 (Gas)
Success for 2021 Dodge Durango (Gas)

TypeError: Can only merge Series or DataFrame objects, a <class 'NoneType'> was passed

In [ ]:
def get_body_type(make, model, year, more_info):
    info_line = f'Additional info: "{more_info}"' if pd.notna(more_info) else "No additional info provided."
    
    prompt = f"""For the {year} {make} {model}, determine its body type (e.g. Sedan, SUV, Coupe, Hatchback, Pickup Truck, Convertible, Wagon, Minivan).

{info_line}

Consider that this exact make, model, and year combination may have a different body type than other years of the same nameplate, since manufacturers sometimes change body style across generations.

If the additional info explicitly states or clearly implies the body type, use that. Otherwise, use your own knowledge of this specific make, model, and year to determine the most likely body type.

Respond in strict JSON format only, no other text:
{{
  "body_type": "<string>"
}}"""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=100,
        messages=[{"role": "user", "content": prompt}]
    )
    
    text = response.content[0].text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    return json.loads(text)

In [ ]:
unique_cars = df[["Year","Make", "Model", "MoreInformation"]].drop_duplicates().reset_index(drop=True)
unique_cars

        Year           Make       Model MoreInformation
0     2022.0        Lincoln     Corsair             NaN
1     2026.0           Jeep    Cherokee             NaN
2     2026.0        Hyundai      Tucson             NaN
3     2024.0          Mazda        CX-5             NaN
4     2021.0           Ford       F-150             NaN
...      ...            ...         ...             ...
4252  2020.0         Nissan  Pathfinder             NaN
4253  2016.0      Chevrolet    Suburban             NaN
4254  2009.0        Porsche      Cayman             718
4255  2009.0  Mercedes-Benz   CLK-Class             NaN
4256  2018.0           Audi          A5       Cabriolet

[4257 rows x 4 columns]

In [ ]:
unique_cars = df[["Make", "Model", "MoreInformation"]].drop_duplicates().reset_index(drop=True)

results = []

for idx, row in unique_cars.iterrows():
    try:
        specs = get_body_type(row["Make"], row["Model"], row["MoreInformation"])
        specs["Make"] = row["Make"]
        specs["Model"] = row["Model"]
        specs["MoreInformation"] = row["MoreInformation"]
        print(f"Success for {row['Make']} {row['Model']}")
        results.append(specs)
    except Exception as e:
        print(f"Failed for {row['Make']} {row['Model']}: {e}")
        results.append({"Make": row["Make"], "Model": row["Model"], 
                        "MoreInformation": row["MoreInformation"], "body_type": None})

body_type_df = pd.DataFrame(results)

Success for Lincoln Corsair
Succceful for Lincoln Corsair
Success for Jeep Cherokee
Succceful for Jeep Cherokee
Success for Hyundai Tucson
Succceful for Hyundai Tucson
Success for Mazda CX-5
Succceful for Mazda CX-5
Success for Ford F-150
Succceful for Ford F-150
Success for Land Rover
Succceful for Land Rover
Success for Honda Passport
Succceful for Honda Passport
Success for Kia Seltos
Succceful for Kia Seltos
Success for Genesis GV70
Succceful for Genesis GV70
Success for Audi S5
Succceful for Audi S5
Success for Mazda Mazda3
Succceful for Mazda Mazda3
Success for Subaru Outback
Succceful for Subaru Outback
Success for Toyota Prius
Succceful for Toyota Prius
Success for BMW X5
Succceful for BMW X5
Success for Subaru WRX
Succceful for Subaru WRX
Success for Infiniti QX60
Succceful for Infiniti QX60
Success for Ford Bronco
Succceful for Ford Bronco
Success for Honda Civic
Succceful for Honda Civic
Success for Nissan Versa
Succceful for Nissan Versa
Success for Mercedes-Benz GLA
Succceful for Mercedes-Benz GLA
Success for Land Rover
Succceful for Land Rover
Success for Volkswagen Taos
Succceful for Volkswagen Taos
Success for Volkswagen Tiguan
Succceful for Volkswagen Tiguan
Success for Kia Carnival
Succceful for Kia Carnival
Success for Porsche Panamera
Succceful for Porsche Panamera
Success for Volkswagen Atlas
Succceful for Volkswagen Atlas
Success for Toyota 4-Runner
Succceful for Toyota 4-Runner
Success for Buick Envision
Succceful for Buick Envision
Success for Toyota RAV
Succceful for Toyota RAV
Success for Mercedes-Benz GLC
Succceful for Mercedes-Benz GLC
Success for Land Rover
Succceful for Land Rover
Success for Audi Q8
Succceful for Audi Q8
Success for Honda Pilot
Succceful for Honda Pilot
Success for BMW X1
Succceful for BMW X1
Success for BMW 8
Succceful for BMW 8
Success for Audi A5
Succceful for Audi A5
Success for Hyundai Elantra
Succceful for Hyundai Elantra
Success for BMW M4
Succceful for BMW M4
Success for Toyota RAV
Succceful for Toyota RAV
Success for Kia Telluride
Succceful for Kia Telluride
Success for Audi A5
Succceful for Audi A5
Success for Toyota Tacoma
Succceful for Toyota Tacoma
Success for BMW 3
Succceful for BMW 3
Success for BMW 5
Succceful for BMW 5
Success for Ford Escape
Succceful for Ford Escape
Success for Hyundai Palisade
Succceful for Hyundai Palisade
Success for Honda CR-V
Succceful for Honda CR-V
Success for Honda Insight
Succceful for Honda Insight
Success for Ford Mustang
Succceful for Ford Mustang
Success for Acura RDX
Succceful for Acura RDX
Success for Toyota Corolla
Succceful for Toyota Corolla
Success for Honda CR-V
Succceful for Honda CR-V
Success for Audi A3
Succceful for Audi A3
Success for MINI 5
Succceful for MINI 5
Success for Audi Q5
Succceful for Audi Q5
Success for Jeep Wrangler
Succceful for Jeep Wrangler
Success for Porsche Macan
Succceful for Porsche Macan
Success for Tesla Model
Succceful for Tesla Model
Success for BMW X6
Succceful for BMW X6
Success for Audi Q7
Succceful for Audi Q7
Success for Land Rover
Succceful for Land Rover
Success for Hyundai Santa
Succceful for Hyundai Santa
Success for Toyota Tundra
Succceful for Toyota Tundra
Success for Acura ILX
Succceful for Acura ILX
Success for Ford Bronco
Succceful for Ford Bronco
Success for Jeep Grand
Succceful for Jeep Grand
Success for Lexus NX
Succceful for Lexus NX
Success for Lexus IS
Succceful for Lexus IS
Success for Volkswagen Golf
Succceful for Volkswagen Golf
Success for RAM 1500
Succceful for RAM 1500
Success for Hyundai Santa
Succceful for Hyundai Santa
Success for Toyota Camry
Succceful for Toyota Camry
Success for Mazda Mazda3
Succceful for Mazda Mazda3
Success for Acura MDX
Succceful for Acura MDX
Success for Land Rover
Succceful for Land Rover
Success for Mazda CX-30
Succceful for Mazda CX-30
Success for Jeep Compass
Succceful for Jeep Compass
Success for Subaru BRZ
Succceful for Subaru BRZ
Success for Nissan Rogue
Succceful for Nissan Rogue
Success for Chevrolet Silverado
Succceful for Chevrolet Silverado
Success for Mercedes-Benz E-Class
Succceful for Mercedes-Benz E-Class
Success for Infiniti QX50
Succceful for Infiniti QX50
Success for Toyota Corolla
Succceful for Toyota Corolla
Success for Mazda CX-9
Succceful for Mazda CX-9
Success for Lincoln Nautilus
Succceful for Lincoln Nautilus
Success for Nissan Pathfinder
Succceful for Nissan Pathfinder
Success for Honda HR-V
Succceful for Honda HR-V
Success for Volkswagen Golf
Succceful for Volkswagen Golf
Success for BMW X2
Succceful for BMW X2
Success for Lexus UX
Succceful for Lexus UX
Success for Mazda CX-50
Succceful for Mazda CX-50
Success for Nissan Frontier
Succceful for Nissan Frontier
Success for Chevrolet Colorado
Succceful for Chevrolet Colorado
Success for Hyundai Kona
Succceful for Hyundai Kona
Success for Toyota Highlander
Succceful for Toyota Highlander
Success for Kia Sorento
Succceful for Kia Sorento
Success for GMC Yukon
Succceful for GMC Yukon
Success for MINI Countryman
Succceful for MINI Countryman
Success for Toyota Sienna
Succceful for Toyota Sienna
Success for Mercedes-Benz C-Class
Succceful for Mercedes-Benz C-Class
Success for BMW 4
Succceful for BMW 4
Success for Chevrolet Blazer
Succceful for Chevrolet Blazer
Success for Lexus TX
Succceful for Lexus TX
Success for Hyundai Tucson
Succceful for Hyundai Tucson
Success for Kia K4
Succceful for Kia K4
Success for Audi Q3
Succceful for Audi Q3
Success for Jeep Wrangler
Succceful for Jeep Wrangler
Success for Mazda CX-70
Succceful for Mazda CX-70
Success for Volvo XC90
Succceful for Volvo XC90
Success for Volvo XC90
Succceful for Volvo XC90
Success for Nissan Z
Succceful for Nissan Z
Success for Mitsubishi Eclipse
Succceful for Mitsubishi Eclipse
Success for Acura TLX
Succceful for Acura TLX
Success for Volkswagen Jetta
Succceful for Volkswagen Jetta
Success for Audi SQ5
Succceful for Audi SQ5
Success for BMW X4
Succceful for BMW X4
Success for Hyundai Venue
Succceful for Hyundai Venue
Success for Nissan Sentra
Succceful for Nissan Sentra
Success for Buick Envista
Succceful for Buick Envista
Success for Mercedes-Benz GLE
Succceful for Mercedes-Benz GLE
Success for Kia Sportage
Succceful for Kia Sportage
Success for Dodge Grand
Succceful for Dodge Grand
Success for Dodge Durango
Succceful for Dodge Durango
Success for Toyota Highlander
Succceful for Toyota Highlander
Success for Ford Explorer
Succceful for Ford Explorer
Success for Audi A3
Succceful for Audi A3
Success for Kia Sorento
Succceful for Kia Sorento
Success for Mazda CX-3
Succceful for Mazda CX-3
Success for BMW 2
Succceful for BMW 2
Success for Tesla Model
Succceful for Tesla Model
Success for Infiniti QX80
Succceful for Infiniti QX80
Success for BMW X3
Succceful for BMW X3
Success for Subaru Crosstrek
Succceful for Subaru Crosstrek
Success for GMC Acadia
Succceful for GMC Acadia
Success for Jeep Wrangler
Succceful for Jeep Wrangler
Success for Jeep Grand
Succceful for Jeep Grand
Success for Hyundai Elantra
Succceful for Hyundai Elantra
Success for Nissan Armada
Succceful for Nissan Armada
Success for Mercedes-Benz C-Class
Succceful for Mercedes-Benz C-Class
Success for Honda Civic
Succceful for Honda Civic
Success for Kia Sorento
Succceful for Kia Sorento
Success for Porsche Cayenne
Succceful for Porsche Cayenne
Success for Mercedes-Benz C-Class
Succceful for Mercedes-Benz C-Class
Success for Volvo XC60
Succceful for Volvo XC60
Success for Toyota Tundra
Succceful for Toyota Tundra
Success for Chevrolet Corvette
Succceful for Chevrolet Corvette
Success for Audi S5
Succceful for Audi S5
Success for Ford Transit
Succceful for Ford Transit
Success for Audi A4
Succceful for Audi A4
Success for Ford Taurus
Succceful for Ford Taurus
Success for Porsche Cayman
Succceful for Porsche Cayman
Success for Dodge Challenger
Succceful for Dodge Challenger
Success for Mercedes-Benz CLA
Succceful for Mercedes-Benz CLA
Success for Hyundai Santa
Succceful for Hyundai Santa
Success for MINI 3
Succceful for MINI 3
Success for Nissan Altima
Succceful for Nissan Altima
Success for Ford Fusion
Succceful for Ford Fusion
Success for Honda Accord
Succceful for Honda Accord
Success for Mitsubishi Outlander
Succceful for Mitsubishi Outlander
Success for Lexus RX
Succceful for Lexus RX
Success for GMC Sierra
Succceful for GMC Sierra
Success for Mazda MX-5
Succceful for Mazda MX-5
Success for Subaru Forester
Succceful for Subaru Forester
Success for Hyundai Kona
Succceful for Hyundai Kona
Success for Hyundai Sonata
Succceful for Hyundai Sonata
Success for Mercedes-Benz GLB
Succceful for Mercedes-Benz GLB
Success for Lexus LX
Succceful for Lexus LX
Failed for Kia Forte: Expecting value: line 1 column 1 (char 0)
Success for Chevrolet Tahoe
Succceful for Chevrolet Tahoe
Success for Volvo XC60
Succceful for Volvo XC60
Success for RAM 3500
Succceful for RAM 3500
Success for Mercedes-Benz CLS-Class
Succceful for Mercedes-Benz CLS-Class
Success for Subaru Ascent
Succceful for Subaru Ascent
Success for Volkswagen Golf
Succceful for Volkswagen Golf
Success for Chevrolet Cruze
Succceful for Chevrolet Cruze
Success for Hyundai Santa
Succceful for Hyundai Santa
Success for GMC Canyon
Succceful for GMC Canyon
Success for Mercedes-Benz GLS
Succceful for Mercedes-Benz GLS
Success for Audi A7
Succceful for Audi A7
Success for Honda Civic
Succceful for Honda Civic
Success for Jeep Gladiator
Succceful for Jeep Gladiator
Success for GMC Terrain
Succceful for GMC Terrain
Success for Ford Focus
Succceful for Ford Focus
Success for Kia Forte
Succceful for Kia Forte
Success for Toyota Corolla
Succceful for Toyota Corolla
Success for Dodge Charger
Succceful for Dodge Charger
Success for BMW 4
Succceful for BMW 4
Success for Audi A4
Succceful for Audi A4
Success for Acura TL
Succceful for Acura TL
Success for Chrysler Pacifica
Succceful for Chrysler Pacifica
Success for Mercedes-Benz SLC
Succceful for Mercedes-Benz SLC
Success for Hyundai Palisade
Succceful for Hyundai Palisade
Success for Toyota Venza
Succceful for Toyota Venza
Success for Ford Expedition
Succceful for Ford Expedition
Success for Audi Q5
Succceful for Audi Q5
Success for Chevrolet Blazer
Succceful for Chevrolet Blazer
Success for BMW M2
Succceful for BMW M2
Success for Chevrolet Traverse
Succceful for Chevrolet Traverse
Success for RAM 2500
Succceful for RAM 2500
Success for Mercedes-Benz AMG
Succceful for Mercedes-Benz AMG
Success for Honda Accord
Succceful for Honda Accord
Success for Ford Mustang
Succceful for Ford Mustang
Success for Nissan Kicks
Succceful for Nissan Kicks
Success for Honda Accord
Succceful for Honda Accord
Success for Toyota Yaris
Succceful for Toyota Yaris
Success for Nissan Qashqai
Succceful for Nissan Qashqai
Success for Infiniti Q60
Succceful for Infiniti Q60
Success for Lincoln Navigator
Succceful for Lincoln Navigator
Failed for Hyundai IONIQ: Expecting value: line 1 column 1 (char 0)
Success for Volkswagen Atlas
Succceful for Volkswagen Atlas
Success for Volkswagen Golf
Succceful for Volkswagen Golf
Success for Cadillac CT5
Succceful for Cadillac CT5
Success for Cadillac XT5
Succceful for Cadillac XT5
Success for Ford Edge
Succceful for Ford Edge
Success for Lexus CT
Succceful for Lexus CT
Success for Ford Flex
Succceful for Ford Flex
Success for Subaru Legacy
Succceful for Subaru Legacy
Success for Infiniti Q50
Succceful for Infiniti Q50
Success for Cadillac Escalade
Succceful for Cadillac Escalade
Success for RAM 1500
Succceful for RAM 1500
Success for Chevrolet Trailblazer
Succceful for Chevrolet Trailblazer
Success for Audi S5
Succceful for Audi S5
Success for BMW 2
Succceful for BMW 2
Success for Mitsubishi Outlander
Succceful for Mitsubishi Outlander
Success for Audi A5
Succceful for Audi A5
Success for Mitsubishi RVR
Succceful for Mitsubishi RVR
Success for Lexus ES
Succceful for Lexus ES
Success for Volkswagen Jetta
Succceful for Volkswagen Jetta
Success for Chevrolet Silverado
Succceful for Chevrolet Silverado
Success for Chevrolet Trax
Succceful for Chevrolet Trax
Success for Hyundai Santa
Succceful for Hyundai Santa
Success for Volkswagen Arteon
Succceful for Volkswagen Arteon
Success for Honda Odyssey
Succceful for Honda Odyssey
Success for RAM ProMaster
Succceful for RAM ProMaster
Success for Hyundai Elantra
Succceful for Hyundai Elantra
Success for BMW X7
Succceful for BMW X7
Success for Volkswagen Jetta
Succceful for Volkswagen Jetta
Success for Honda Ridgeline
Succceful for Honda Ridgeline
Success for Audi A8
Succceful for Audi A8
Success for Lincoln Aviator
Succceful for Lincoln Aviator
Success for Ford Maverick
Succceful for Ford Maverick
Success for Jeep Wrangler
Succceful for Jeep Wrangler
Success for Kia Sportage
Succceful for Kia Sportage
Success for Chevrolet Bolt
Succceful for Chevrolet Bolt
Success for Chevrolet Equinox
Succceful for Chevrolet Equinox
Success for Cadillac XT4
Succceful for Cadillac XT4
Success for Volkswagen Passat
Succceful for Volkswagen Passat
Success for Toyota Grand
Succceful for Toyota Grand
Success for Ford Escape
Succceful for Ford Escape
Success for Hyundai Tucson
Succceful for Hyundai Tucson
Success for Cadillac Escalade
Succceful for Cadillac Escalade
Success for Lincoln MKC
Succceful for Lincoln MKC
Success for Hyundai Santa
Succceful for Hyundai Santa
Success for Mazda CX-90
Succceful for Mazda CX-90
Success for Lincoln Navigator
Succceful for Lincoln Navigator
Success for GMC Savana
Succceful for GMC Savana
Success for Ford Ranger
Succceful for Ford Ranger
Success for Nissan Murano
Succceful for Nissan Murano
Success for Honda Accord
Succceful for Honda Accord
Success for Mazda CX-90
Succceful for Mazda CX-90
Success for Chevrolet Suburban
Succceful for Chevrolet Suburban
Success for Toyota 4-Runner
Succceful for Toyota 4-Runner
Success for Chevrolet Malibu
Succceful for Chevrolet Malibu
Success for Chrysler 300
Succceful for Chrysler 300
Success for Mercedes-Benz A-Class
Succceful for Mercedes-Benz A-Class
Success for Chevrolet Silverado
Succceful for Chevrolet Silverado
Success for GMC Yukon
Succceful for GMC Yukon
Success for GMC Sierra
Succceful for GMC Sierra
Success for Ford F-250
Succceful for Ford F-250
Success for BMW X5
Succceful for BMW X5
Success for Dodge Journey
Succceful for Dodge Journey
Success for Kia Rio
Succceful for Kia Rio
Success for Chrysler Grand
Succceful for Chrysler Grand
Success for Buick Encore
Succceful for Buick Encore
Success for Acura Integra
Succceful for Acura Integra
Success for Buick Enclave
Succceful for Buick Enclave
Success for Chevrolet Silverado
Succceful for Chevrolet Silverado
Success for Jeep Grand
Succceful for Jeep Grand
Success for Toyota C-HR
Succceful for Toyota C-HR
Success for Hyundai ACCENT
Succceful for Hyundai ACCENT
Success for GMC Sierra
Succceful for GMC Sierra
Success for Volvo XC40
Succceful for Volvo XC40
Success for Kia EV9
Succceful for Kia EV9
Success for Chevrolet Bolt
Succceful for Chevrolet Bolt
Success for Kia Niro
Succceful for Kia Niro
Failed for Subaru Uncharted: Expecting value: line 1 column 1 (char 0)
Success for Mazda CX-70
Succceful for Mazda CX-70
Success for GMC HUMMER
Succceful for GMC HUMMER
Success for Ford F-350
Succceful for Ford F-350
Success for Mazda Mazda6
Succceful for Mazda Mazda6
Success for GMC HUMMER
Succceful for GMC HUMMER
Success for Honda Fit
Succceful for Honda Fit
Success for Hyundai Elantra
Succceful for Hyundai Elantra
Success for GMC Sierra
Succceful for GMC Sierra
Success for Ford Police
Succceful for Ford Police
Success for Audi A6
Succceful for Audi A6
Success for Chevrolet Silverado
Succceful for Chevrolet Silverado
Success for Mercedes-Benz S-Class
Succceful for Mercedes-Benz S-Class
Success for Chevrolet Bolt
Succceful for Chevrolet Bolt
Success for Chevrolet Camaro
Succceful for Chevrolet Camaro
Success for Kia Soul
Succceful for Kia Soul
Success for Ford Fusion
Succceful for Ford Fusion
Success for Chevrolet Express
Succceful for Chevrolet Express
Success for BMW 3
Succceful for BMW 3
Success for BMW 7
Succceful for BMW 7
Success for Jeep Grand
Succceful for Jeep Grand
Success for Mazda Mazda2
Succceful for Mazda Mazda2
Success for Toyota HiAce
Succceful for Toyota HiAce
Success for Toyota Corolla
Succceful for Toyota Corolla
Success for Chevrolet Malibu
Succceful for Chevrolet Malibu
Success for Infiniti G
Succceful for Infiniti G
Success for Acura ADX
Succceful for Acura ADX
Success for Honda Civic
Succceful for Honda Civic
Success for Cadillac Lyriq
Succceful for Cadillac Lyriq
Success for Lexus IS
Succceful for Lexus IS
Success for Lexus RC
Succceful for Lexus RC
Success for Land Rover
Succceful for Land Rover
Success for Kia Niro
Succceful for Kia Niro
Failed for Subaru Trailseeker: Expecting value: line 1 column 1 (char 0)
Success for Subaru Impreza
Succceful for Subaru Impreza
Success for Mitsubishi Lancer
Succceful for Mitsubishi Lancer
Success for Hyundai Sonata
Succceful for Hyundai Sonata
Success for Nissan Kicks
Succceful for Nissan Kicks
Success for Toyota Camry
Succceful for Toyota Camry
Success for Toyota GR
Succceful for Toyota GR
Success for Volvo XC90
Succceful for Volvo XC90
Success for Volvo XC40
Succceful for Volvo XC40
Success for Toyota Crown
Succceful for Toyota Crown
Success for Kia K5
Succceful for Kia K5
Success for Infiniti QX56
Succceful for Infiniti QX56
Success for Mercedes-Benz A-Class
Succceful for Mercedes-Benz A-Class
Success for Volkswagen Passat
Succceful for Volkswagen Passat
Success for Audi S7
Succceful for Audi S7
Success for Kia Rio
Succceful for Kia Rio
Success for Chrysler Pacifica
Succceful for Chrysler Pacifica
Success for Chevrolet Corvette
Succceful for Chevrolet Corvette
Success for Kia Soul
Succceful for Kia Soul
Success for Mazda CX-70
Succceful for Mazda CX-70
Success for Volvo XC90
Succceful for Volvo XC90
Success for Volvo EX30
Succceful for Volvo EX30
Success for Honda Prelude
Succceful for Honda Prelude
Success for Kia EV4
Succceful for Kia EV4
Success for Jeep Wagoneer
Succceful for Jeep Wagoneer
Success for Acura ZDX
Succceful for Acura ZDX
Success for Acura RLX
Succceful for Acura RLX
Success for Acura TSX
Succceful for Acura TSX
Success for Audi A4
Succceful for Audi A4
Success for Audi SQ5
Succceful for Audi SQ5
Success for Audi S4
Succceful for Audi S4
Success for Audi RS
Succceful for Audi RS
Success for Audi RS7
Succceful for Audi RS7
Success for Audi Q8
Succceful for Audi Q8
Success for Audi RS5
Succceful for Audi RS5
Success for Audi RS3
Succceful for Audi RS3
Success for Audi RS3
Succceful for Audi RS3
Success for Audi A6
Succceful for Audi A6
Success for Audi S5
Succceful for Audi S5
Success for Audi RS5
Succceful for Audi RS5
Success for Audi R8
Succceful for Audi R8
Success for Audi RS5
Succceful for Audi RS5
Success for Audi S3
Succceful for Audi S3
Success for Audi RS6
Succceful for Audi RS6
Success for Audi TTS
Succceful for Audi TTS
Success for Audi S6
Succceful for Audi S6
Success for Audi TT
Succceful for Audi TT
Success for Audi Q4
Succceful for Audi Q4
Success for Audi SQ7
Succceful for Audi SQ7
Success for Audi Q6
Succceful for Audi Q6
Success for BMW iX
Succceful for BMW iX
Success for BMW M3
Succceful for BMW M3
Success for BMW i4
Succceful for BMW i4
Success for BMW Z4
Succceful for BMW Z4
Success for BMW i8
Succceful for BMW i8
Success for BMW M6
Succceful for BMW M6
Success for BMW 1
Succceful for BMW 1
Success for BMW X3
Succceful for BMW X3
Success for BMW M5
Succceful for BMW M5
Success for BMW X6
Succceful for BMW X6
Success for BMW M8
Succceful for BMW M8
Success for BMW i5
Succceful for BMW i5
Success for BMW i7
Succceful for BMW i7
Success for BMW 8
Succceful for BMW 8
Success for BMW M6
Succceful for BMW M6
Success for Buick Encore
Succceful for Buick Encore
Success for Buick Verano
Succceful for Buick Verano
Success for Buick Regal
Succceful for Buick Regal
Success for Buick Lacrosse
Succceful for Buick Lacrosse
Success for Buick Regal
Succceful for Buick Regal
Success for Buick Allure
Succceful for Buick Allure
Success for Cadillac Optiq
Succceful for Cadillac Optiq
Success for Cadillac XT6

In [ ]:
body_type_df.to_csv("BodyType.csv")